version: "3"
services:
  spring-tpfoyer:
    image: nour056/tpfoyer
    ports:
      - "8089:8089"
    networks:
      - foyer
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    volumes:
      - /home/mysql/nourdata:/var/lib/mysql:rw
    networks:
      - foyer
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db

  prometheus:
    image: nour056/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Ce fichier configure Prometheus
    networks:
      - foyer

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - foyer
    depends_on:
      - prometheus

networks:
  foyer:
