version: "3"
services:
  spring-tpfoyer:
    image: nour056/tpfoyer
    ports:
      - "8089:8089"
    networks:
      - foyer
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/nourdata:/var/lib/mysql:rw
    networks:
      - foyer
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db

networks:
  foyer: