version: '3'
services:
  app:
    build: .
    ports:
      - "8082:8082"
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: 5ERP-BI7_G2_tpFoyer
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql-data: