version: "3.8"

services:
  spring-tpfoyer:
    image: dhiaezzine/app-foyer:1.0.0
    container_name: app-foyer-container-${HOSTNAME}
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/foyer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysqldb
    restart: on-failure

  mysqldb:
    image: mysql:8
    container_name: mysqldb-container-${HOSTNAME}
    volumes:
      - /home/mysql/dhiaezzine:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foyer
