

version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - myappNetwork
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    image: dhiaezzine/app-foyer:1.0.0
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    networks:
      - myappNetwork





networks:
  myappNetwork:

volumes:
  mysql-data: