    version: "3.8"

    services:
      mysqlDb:
        image: mysql:5.7
        restart: unless-stopped
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=foyer
        ports:
          - "3306:3306"
        volumes:
          - db:/var/lib/mysql
      app-foyer:
          depends_on:
            - mysqlDb
          image: nour056/tpfoyer:1.0.0
          restart: on-failure
          ports:
            - "8089:8089"
          environment:
            SPRING_APPLICATION_JSON: '{
             "spring.datasource.url": "jdbc:mysql://mysqlDb:3306/foyer?createDatabaseIfNotExist=true",
             "spring.datasource.username": "root",
             "spring.datasource.password": "root",
             "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
             "spring.jpa.hibernate.ddl-auto": "update"
           }'
          stdin_open: true
          tty: true


  volumes:
    db: