version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foyer
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-foyer:
    depends_on:
      - mysqldb
    image: dhiajr/dhiajmour-5bi7-g2-foyer:1.0.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
     "spring.datasource.url": "jdbc:mysql://mysqldb:3306/foyer",
     "spring.datasource.username": "root",
     "spring.datasource.password": "root",
     "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
     "spring.jpa.hibernate.ddl-auto": "update"
   }'
    stdin_open: true
    tty: true
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

volumes:
  db: