global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-tpfoyer'
    static_configs:
      - targets: ['spring-tpfoyer:8082']

  - job_name: 'mysqldb'
    static_configs:
      - targets: ['mysqldb:3306']
